### ISSUE TITLE
RT-Thread 4.1.0 软件包直接编译报错  "time_t" is undefined

### ISSUE THREAD

**Issue by ousugo** [Prry/rtt-ds3231#4]
使用环境：
- RT-Thread 4.1.0
- ENV：1.2.0
- Keil ：5.36.0

操作步骤：
1. `pkgs --update` 引入软件包
2. board/Kconfig 文件加入以下内容并开启：
```
    config RT_USING_RTC
            bool "Enable DS3231"
            select BSP_USING_I2C8
            default n
```
3. `scons --target=mdk5` 生成工程

此时进行编译的时候，会报以下错误：
```
packages\ds3231-latest\ds3231.c(138): error:  #20: identifier "time_t" is undefined`
....
packages\ds3231-latest\ds3231.c(242): error:  #20: identifier "uint8_t" is undefined
```

临时解决方法需要手动在文件 `ds3231.c` 中加入 `#include <sys/time.h`。

想请教下，上诉问题是我的操作步骤有问题导致的，还是因为 RT-Thread 的版本进行了更新导致的？

自己找原因的过程中，有注意到 [[components/libc] Move time() and clock() function to libc time.c](https://github.com/RT-Thread/rt-thread/commit/5501ec36cb0e561e890f331485389c0025374da5#) 这个提交将 `time_t time(time_t *t)` 从 `components/drivers/rtc/rtc.c` 移动到了 `components/libc/compilers/common/time.c`，不知与我的问题是否有关系？

**Comment by mysterywolf** [comment]
https://github.com/Prry/rtt-ds3231/pull/5
